### ISSUE TITLE
RoundToSigFigs fails when x is numpy.matrix

### ISSUE THREAD

**Issue by tantecky** [odysseus9672/SELPythonLibs#1]
Error is occurring on line `absx = xsgn * x`, because `np.dot` is working differently for `numpy.matrix`. My quick workaround is to convert an matrix to an ndarray before multiplication:
```
x = np.asarray(x)
xsgn = np.sign(x)
absx = xsgn * x
```

**Comment by odysseus9672** [comment]
Thank you for the interest. I put the call to `np.asarray` into a type checking conditional because I want to try to return the same type as `x` in as many cases as possible. For that same reason, I've also made it so that the returned result is a matrix if `x` is a matrix.

Let me know whether or not this works as intended for you.

**Comment by tantecky** [comment]
I've tested on my case and it is working without a problem. So thank you for the fix!
